### ISSUE TITLE
nieuwe wijken update 6/2021

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/gebiedsniveaus#22]
~~[aanvulling voorjaar 2021.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/6242423/aanvulling.voorjaar.2021.xlsx)~~
[aanvulling voorjaar 2021_versie 20210621.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/6685369/aanvulling.voorjaar.2021_versie.20210621.xlsx)

**Comment by HildeC** [comment]
ik ben bezig met Oostkamp.
2 probleempjes, die ontstaan door de intekening van de sectoren.
Wijk Oostkamp bestaat zogezegd uit 2 delen, omdat een stat sector van steenbrugge nog op een dunne spie doorloopt (is eigenlijk de autostrade) in de feiten loopt dit in elkaar over. is dit een probleem?
ook erkegem is zo'n apart geval, twee stat sectoren die door de jaren heen naar 1 wijk geevolueerd zijn, maar ook hier loopt een baan door, die tot andere sector behoort. op die manier wijk ik af van de regel: samenhangende sectoren. maar in de feiten behoort de onderste sector van erkegem niet tot nieuwenhove, niet tot oostkamp en niet tot herstberge. huidig voorstel is maw woorden best aansluitend bij realiteit op het terrein.
mag voor oostkamp dit zo behouden worden?

**Comment by joostschouppe** [comment]
Indeling Sint-Truiden:
[gemeentegedragen_wijken.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/6655812/gemeentegedragen_wijken.xlsx)

**Comment by joostschouppe** [comment]
[Aanpassingen_wijkgrenzen_VB.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/6700392/Aanpassingen_wijkgrenzen_VB.xlsx)
