### ISSUE TITLE
Brusselse wijken in PinC

### ISSUE THREAD

**Issue by VickyVB** [provinciesincijfers/gebiedsniveaus#25]
Kunnen de Brusselse wijken (gebruikt door het BISA) ingevoerd worden in PinC. Vlaams-Brabant wil de indeling wel aanleveren.

**Comment by joostschouppe** [comment]
Sure! Als jullie tegen morgenavond een tabel bezorgen conform [de afspraken hier](https://github.com/provinciesincijfers/gebiedsniveaus/tree/master/gemeente_statsec_wijken), dan kan ik die zelfs nu nog meenemen

**Comment by Tine-VB** [comment]
Komt in orde tegen morgennamiddag.
