### ISSUE TITLE
deelgemeenten Heuvelland

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/gebiedsniveaus#27]
in kader van voorbereiding gemeentegedragen wijken in Heuvelland, kwam ik tot de vaststelling dat de sectoren van De Klijte (33029H) bij deelgemeente Loker (33039F) zijn gevoegd. is hier een reden voor?

**Comment by joostschouppe** [comment]
Als je [dit erop naleest](https://github.com/provinciesincijfers/gebiedsniveaus/blob/master/deelgemeenten/methodiek.md), lijkt me de enige logische conclusie dat het NGI niet vindt dat de De Klijte een deelgemeente is. Die zijn [hier downloadbaar](https://www.ngi.be/website/aanbod/digitale-geodata/vectoriele-referentiegegevens/) . Een snelle visualisatie toont dat dat effectief ook zo is:
![afbeelding](https://user-images.githubusercontent.com/10122639/130592820-12ba3949-c4e3-40ed-ac45-dde272a59321.png)
