### ISSUE TITLE
nieuwe wijknamen Sint-Katelijne-Waver

### ISSUE THREAD

**Issue by Lievendr** [provinciesincijfers/gebiedsniveaus#36]
12035A0 = Centrum
12035A1=  Pasburg-Nieuwendijk
12035A2 = Elzestraat
12035BO = Waver

**Comment by joostschouppe** [comment]
[gemeentegedragen_wijken.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/8004302/gemeentegedragen_wijken.xlsx)
