### ISSUE TITLE
Gemeente-wijken in de running voor release 6/2022

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/gebiedsniveaus#39]
Deadline voor definitieve, reeds gevalideerde versie: 31/5/2022

gemeente | prov | issue | status
-- | -- | -- | --
Sint-Katelijne-Waver | AN | #36 | ontvangen, niet gecontroleerd
Mortsel | AN |  | contact via WMSW: versie ontvangen, opvolging door ons nodig
Geel | AN |  |  voorstel bijna rond
Duffel | AN |  |  in gesprek
Herent | VB | | contact VMSW: ze zijn er al een tijdje mee bezig
Nieuwerkerken | LI | #35 | enkel namen geven aan nis7-wijken (na oproep Opgroeien)
Riemst | LI |  | in gesprek
Heusden-Zolder | LI |  | eerste versie gekregen eind april
Tongeren | LI |  | in gesprek
Bilzen | LI |  | in gesprek
Gingelom | LI |  | in gesprek
Leopoldsburg | LI |  | in gesprek
As | LI |  | in gesprek
Kuurne | WV | | contact VMSW: ze zijn er al mee bezig
Harelbeke | WV | | in opmaak
Zottegem | OV | | na oproep Opgroeien begonnen
Geraardsbergen | OV | |  na oproep Opgroeien begonnen
Zele | OV | | na oproep opgroeien begonnen
Eeklo | OV | | draftversie in orde, wordt eerst nog intern geëvalueerd

**Comment by joostschouppe** [comment]
Definitief voorstel Mortsel
[gemeentegedragen_wijken8maart2022.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/8207986/gemeentegedragen_wijken8maart2022.xlsx)
[BESLUIT wijken.pdf](https://github.com/provinciesincijfers/gebiedsniveaus/files/8207992/BESLUIT.wijken.pdf)

**Comment by HanneODB-VLBR** [comment]
Halle, Huldenberg, Opwijk, Roosdaal & Wemmel ontvangen, gecontroleerd & goedgekeurd
Galmaarden: ontvangen & gecontroleerd, maar moet nog worden aangepast
Affligem, Beersel, Bertem, Boutersem, Diest, Dilbeek, Geetbets, Herent, Holsbeek, Kapelle-op-den-bos, Kraainem, Liedekerke, Linter, Overijse, Pepingen, Rotselaar, Sint-Genesius-Rode, Sint-Pieters-Leeuw, Ternat, Tervuren, Tielt-Winge, Tienen, Tremelo, Wezembeek-Oppem & Zoutleeuw allemaal gecontacteerd, van sommige reactie (gaande van 'ik heb hier geen tijd/geen interesse in' tot 'ik neem het op / ik stuur het naar mijn collega'), van vele (nog) geen reactie. Ook regiomedewerkers Opgroeien ingeschakeld om mee te zoeken naar alternatieve contacten in 'hun' gemeenten.

**Comment by HildeC** [comment]
definitief voorstel van Harelbeke en Deerlijk
[Pinc Wijken Harelbeke en Deerlijk.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/8706930/Pinc.Wijken.Harelbeke.en.Deerlijk.xlsx)

**Comment by HildeC** [comment]
[Ledegem en Zedelgem.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/8812922/Ledegem.en.Zedelgem.xlsx)
definitief voorstel PinC wijken Zedelgem en Ledegem

**Comment by KoenSnyers** [comment]
Update Limburgse gemeenten:

Heusden-Zolder: is definitief in orde.
Nieuwerkerken: namen zijn al gegeven aan nis7-wijken, nog toevoegen aan wijkindeling ook (zie https://github.com/provinciesincijfers/gebiedsniveaus/issues/35)
De gemeenten Tongeren, Bilzen, Gingelom, Leopoldsburg en As hebben laten weten tot nader order geen wijkindeling aan te maken.

@joostschouppe

**Comment by HildeC** [comment]
en Wielsbeke
[wielsbeke.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/8938709/wielsbeke.xlsx)

**Comment by HanneODB-VLBR** [comment]
Vlaams-Brabantse gemeenten in de running voor volgende update (is dat voor januari 2023?):
- Affligem: in gesprek met gemeente
- Beersel: wijkindeling klaar, nog te verifiëren door college
- Bertem: in gesprek met gemeente
- Diest: probleem met voorgestelde wijkindeling, voorlopig on hold
- Dilbeek: wijkindeling klaar, nog te verifiëren door college
- Kapelle-op-den-bos: in gesprek met gemeente
- Kraainem: in gesprek met gemeente
- Liedekerke: in gesprek met gemeente
- Tervuren: in gesprek met gemeente
- Tienen: wijkindeling klaar + geverifieerd, was alleen nét iets te laat voor release van 6/2022
- Tremelo: in gesprek met gemeente

Eventueel ook nuttige info: wijkindelingsgesprekken die compleet niet van de grond geraken/zijn vastgelopen:
-Geetbets: tijdsgebrek, personeelsgebrek
-Oud-Heverlee: tijdsgebrek, personeelsgebrek
-Machelen: gebondenheid aan statistische sectoren is onoverkomelijk voor gemeente

**Comment by Lievendr** [comment]
Herselt
[Herselt_PinC.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/9196495/Herselt_PinC.xlsx)
