### ISSUE TITLE
Gemeentegedragen wijken release 12/2022

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/gebiedsniveaus#40]
Volgende deadline 1/12/2022
Joost doet eerste verwerking uiterlijk 2 december. Idealiter zijn er op dat moment geen probleemgevallen meer.
Indien er wel nog probleemgevallen zijn, dan worden eventuele correcties verwerkt op 12/12 (dus deadline voor gecorrigeerde input 9/12)

**Comment by Lievendr** [comment]
Herselt heeft definitief voorstel
[Herselt_PinC.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/9196475/Herselt_PinC.xlsx)
l

**Comment by Lievendr** [comment]
Herselt
[Herselt_PinC.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/9198019/Herselt_PinC.xlsx)

**Comment by HanneODB-VLBR** [comment]
Dag allen

HOPLR bezorgde ons de wijkindelingen die zij reeds verzamelden. Het is zeker niet de bedoeling dat wij onze bestaande wijkindelingen hiernaar gaan wijzigen, als je al een wijkindeling hebt voor een gemeente blijft die zoals ze is.  Maar, als je een wijkindelingsproces opstart met een nieuwe gemeente die ook al een HOPLR indeling heeft, is het wel nuttig hiernaar te kijken en dit te gebruiken als inspiratie (in de mate van het mogelijke, want zij hanteren andere voorwaarden dan wij. Zo worden de statsec grenzen er niet in gerespecteerd, bijvoorbeeld). HOPLR gaat hetzelfde doen als zij een nieuw proces opstarten met een gemeente waarvoor wij al een indeling hebben. Op die manier hopen we tot wijkindelingen te komen die toch niet al te ver uiteen liggen, wat interessanter is voor iedereen. Hierbij ook nog hun criteria die ze hanteren:
_"De criteria die wij gebruiken voor het bepalen van een buurtindeling:
•	1000 tot 3000 huishoudens groot (op landelijke plekken zal dit gevoelig lager liggen)
•	Logische en natuurlijke grenzen
o	steenweg
o	rivier
o	weiland
o	...
•	Woonkernen samen houden
•	Dorpskernen aanhouden
•	Herkenbare naam
"_
Ze bezorgden hun bestanden in KML format. Je kan deze ofwel openen in Google Earth (links in het menu 'layer toevoegen' kiezen en dan 'KML file openen', en dan opgeslagen file selecteren) ofwel meteen converteren naar shp zodat je het kan openen in ArcGIS of QGIS (bijvoorbeeld gratis online via https://mygeodata.cloud/converter/kml-to-shp). 
[Wijkindelingen HOPLR.zip](https://github.com/provinciesincijfers/gebiedsniveaus/files/9631894/Wijkindelingen.HOPLR.zip)

**Comment by HildeC** [comment]
update WVL:
3 bijkomende wijken: Ingelmunster, Mesen en Torhout
[gemeentegedragen_wijken_aanvulling WVL december 2022.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/10081578/gemeentegedragen_wijken_aanvulling.WVL.december.2022.xlsx)

**Comment by joostschouppe** [comment]
Na afronden van update zeker ook IMA op de hoogte brengen

**Comment by EmielGrimonprez** [comment]
Update Oost-Vlaanderen:
Wijkindeling Zottegem 
[gemeentegedragen_wijken - Zottegem.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/10113327/gemeentegedragen_wijken.-.Zottegem.xlsx)

**Comment by HanneODB-VLBR** [comment]
Hierbij de nieuwe wijkindelingen voor Vlaams-Brabant voor de update:
Boutersem
Dilbeek
Kapelle-op-den-Bos
Kortenaken
Liedekerke
Rotselaar
Ternat
[gemeentegedragen_wijken_vlbr_20221129.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/10114091/gemeentegedragen_wijken_vlbr_20221129.xlsx)
