### ISSUE TITLE
Gemeentegedragen wijken 6/2023

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/gebiedsniveaus#47]
Deadline uiterlijk 1 juni, liefst reeds nagekeken.
Nadien één week tijd voor eventuele correcties, dus publicatie kort na 8 juni

**Comment by EmielGrimonprez** [comment]
Definitief voorstel gemeentegedragen wijkindeling Zottegem
[gemeentegedragen wijken -Zottegem (def).xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/10383049/gemeentegedragen.wijken.-Zottegem.def.xlsx)

**Comment by HildeC** [comment]
8 bijkomende gemeenten: Alveringem, Anzegem, Avelgem, Heuvelland, Koekelare,  Koksijde, Kortemark, Poperinge
In Koksijde is er 1 dorpskern, die uit 1 sector bestaat, die apart als wijk staat, maar wat errond ligt is buitengebied. dus dit is de beste keuze lijkt me.
[gemeentegedragen wijken voorjaar 2023.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/11419145/gemeentegedragen.wijken.voorjaar.2023.xlsx)

**Comment by HildeC** [comment]
hierbij de gemeentegedragen wijken - aanvulling voorjaar 2023
er zijn 7 gemeenten: Alveringem, Avelgem, Heuvelland, Koekelare, Koksijde Kortemark en Poperinge
ik Koksijde is er een wijk die uit 1 sector bestaat (Wulpen - sect 38014C00-) alle omliggende sectoren behoren tot het buitengebied (en de kern Wulpen  bestaat maar uit 1 stat. sector).
[gemeentegedragen wijken voorjaar 2023_2.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/11420754/gemeentegedragen.wijken.voorjaar.2023_2.xlsx)

**Comment by rudymarynissen** [comment]
HOVE
Checklist Hove:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: NOK, 1 wijk onder de 500, maar verantwoord aangezien ze deze wijknamen ook effectief gebruiken in hun werking en met deze aanpassing ingang kunnen laten vinden bij hun partners.
Contactpersoon PinC: OK
BAARLE-HERTOG
Checklist Baarle-Hertog:
Respect voor sectorgrenzen en gemeentegrenzen: NOK -> enclave-gemeente
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: NOK, Niet aaneengesloten want bestaande uit enclaves EN 2 wijken van 1 SS, maar geen beter alternatief mogelijk, 
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: NOK, 2 wijken met minder dan 250, maar geen beter alternatief mogelijk
Contactpersoon PinC: OK
BALEN
Checklist Balen:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: OK
Contactpersoon PinC: OK
BERLAAR
Checklist Berlaar:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK 
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: NOK, 2 wijk met minder dan 200 inwoners, maar uit telefonisch contact blijkt dat er geen beter alternatief is zolang de SS grenzen niet aangepast kunnen worden. Ze willen deze wijknaam absoluut ingang laten vinden.
Contactpersoon PinC: OK
HERENTALS
Checklist Herentals:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: NOK, 2 wijken (Morkhoven en Diependaal) van 1 SS, maar geen beter alternatief mogelijk, 
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: OK
Contactpersoon PinC: OK
NIJLEN
Checklist Nijlen:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: NOK, wijk Tibour: geen beter alternatief mogelijk
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijken voldoende groot: NOK, wijk Tibour heeft 207 inwoners, geen beter alternatief mogelijk om gedragenheid bij Nijlen te verkrijgen
Contactpersoon PinC: OK
WIJNEGEM
Checklist Wijnegem:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK, gebruiken wijken zeer weinig…
Wijknamen: OK
Wijken voldoende groot: OK
Contactpersoon PinC: OK
WESTERLO
Had al een Arvastat indeling maar zou die graag wijzigen.
Checklist Westerlo:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: OK
Westerlo vraagt een aanpassing van de grenzen van de statistische sectoren i.f.v. een goede afstemming met o.a. hun kieswijken, nu is geopteerd voor de best mogelijke match maar die is niet ideaal.)
Contactpersoon PinC: OK
KONTICH
Checklist Kontich:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: OK
Contactpersoon PinC: OK
BOECHOUT
Checklist Boechout:
Respect voor sectorgrenzen en gemeentegrenzen: OK
Elke sector moet exclusief toegewezen worden aan 1 wijk: OK
Wijken bestaan uit meerdere aaneensluitende sectoren: OK
1 wijk moet onbekend zijn om als ‘restcategorie’ voor niet localiseerbare data: OK
Wijkindeling aftoetsen bij verschillende diensten om bruikbaarheid te verhogen (ruimtelijke ordening, wonen, welzijn, buurtwerkingen,…): OK
Wijknamen: OK
Wijken voldoende groot: NOK, 1 wijk met maar 365 inwoners, maar uit telefonisch contact blijkt dat er geen beter alternatief is zolang de SS grenzen niet aangepast kunnen worden. 
Contactpersoon PinC: OK


[gemeentegedragen_wijken_provant_20230531.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/11611378/gemeentegedragen_wijken_provant_20230531.xlsx)

**Comment by EmielGrimonprez** [comment]
Bij deze de update voorjaar 2023 voor Oost-Vlaanderen: 
[gemeentegedragen_wijken_provovl_20230531.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/11615113/gemeentegedragen_wijken_provovl_20230531.xlsx)

Volgende gemeenten kregen een gemeentegedragen wijkindeling:
- Deinze
- Dendermonde
- Gavere
- Kluisbergen
- Maarkedal
- Zottegem

**Comment by HanneODB-VLBR** [comment]
En hier die van Vlaams-Brabant, volgende gemeenten:
- Beersel
- Bertem
- Oud-Heverlee
- Sint-Pieters-Leeuw
[gemeentegedragen_wijken_vlbr_20230601.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/11622961/gemeentegedragen_wijken_vlbr_20230601.xlsx)
