### ISSUE TITLE
aanpassing werkingsgebieden woonmaatschappijen

### ISSUE THREAD

**Issue by HildeC** [provinciesincijfers/gebiedsniveaus#58]
in juni werden de laatste beslissingen ivm de werkingsgebieden woonmaatschappijen genomen. in Oost-Vlaanderen is er alvast een wijziging (Vlaamse Ardennen wordt 1 maatschappij)

De kaart is de indeling zoals op 23 juni goedgekeurd.
[Vorming_woonmaatschappijen_20230623_ntqpzt.pdf](https://github.com/provinciesincijfers/gebiedsniveaus/files/12519969/Vorming_woonmaatschappijen_20230623_ntqpzt.pdf)

Ik kreeg van Eric Tjampens (wonen OVL) ook de vraag om de namen van de woonmaatschappijen aan te passen in PinC.
Maar wat doen we met de naamgeving? Bv dender-midden heet nu Stek92
     Waasland midden heet nu WoonST
     Werkingsgebied Gent-zuid wordt Dimensa

Een vraagje om over te beslissen: houden we de bestaande namen van de gebiedsindeling, of geven we aan de gebiedsindeling de naam van de betreffende woonmaatschappij? 
De namen van de woonmaatschappijen staan niet op de kaart met de werkingsgebieden. Als we opteren voor de namen van de woonmaatschappijen, dan moeten we wel nog een rondvraag doen in elke provincie.

**Comment by Emilien-Dupont** [comment]
zie https://github.com/provinciesincijfers/PinC-taakopvolging/issues/410
