### ISSUE TITLE
ggw7: "wijk onbekend" staat niet altijd laatste binnen een gemeente

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/gebiedsniveaus#6]
ggw7: "wijk onbekend" staat niet altijd laatste binnen een gemeente - wellicht omdat zowel "onb" als "zzzz" gebruikt wordt om die aan te geven. Bij statsec doet zich dit ook voor!

Bij (Pelt) fusie van Overpelt en Neerpelt geen Wijk Onbekend

Onderwerp gebiedscodes en gebiedsnaam ontbreken voor ggw7

Aggregatietabel ggw7-gemeente2018 is fout

**Comment by StefanJacques** [comment]
Bij Lummen 71037
wijk (ggw7) Geneiken wijzigen naar GEENEIKEN
wijk (ggw7) Thiewinkel wijzigen naar TIEWINKEL
