### ISSUE TITLE
twee extra categorieën wijken

### ISSUE THREAD

**Issue by Emilien-Dupont** [provinciesincijfers/gebiedsniveaus#68]
We voegen twee extra categorieën toe. Is er geen consensus binnen een lokaal bestuur, of is er geen reactie meer zonder een duidelijke ‘nee’, dan maken we zelf een indeling. De namen van de wijken zijn dan: wijk 1, wijk 2 etc. Het label: wijkindeling – voorstel provincie. Wil het lokaal bestuur geen wijkindeling, dan maken we een wijk op basis van de gemeente met als naam: ‘naam gemeente (wijk)’ en label: ‘geen wijkindeling beschikbaar’. De twee extra categorieën duiden we uitgebreid in de metadata, bv. geen wijkindeling beschikbaar – mogelijke redenen: ...

**Comment by Tine-VB** [comment]
"Wil het lokaal bestuur geen wijkindeling, dan maken we een wijk op basis van de gemeente met als naam: ‘naam gemeente (wijk)’ en label: ‘geen wijkindeling beschikbaar’. "
Graag dit nog eens bespreken op IPWG of redactiegroep. We (vooral Filip en ik 😊) zijn het er helemaal niet mee eens dat de gemeente als enige wijk wordt genomen als een gemeente expliciet zou aangeven geen wijkindeling te willen. Buiten de gemeente zijn er nog andere gebruikers voor wie de huidige indeling in wijken op basis van de sectoren toch nuttig kan zijn, inclusief wijzelf vanuit D&A. Voor sommige data is een statistische sector echt wel te klein als gebied, en dan zou er enkel nog de (deel)gemeente resten. We zouden dus liever gewoon de categorie 'geen gemeentegedragen wijkindeling beschikbaar' behouden,  ongeacht wat de reden daarvoor is.
