### ISSUE TITLE
Correctie toeristische regios

### ISSUE THREAD

**Issue by joostschouppe** [provinciesincijfers/gebiedsniveaus#7]
Zeebrugge benaderen op basis van statsec die de postcode benaderen
- updaten geometrie
- updaten aggregatietabel
[REFNIS_POSTCODE.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/5377289/REFNIS_POSTCODE.xlsx)

Zie ook https://github.com/provinciesincijfers/PinC-taakopvolging/issues/122#issuecomment-731559179

**Comment by joostschouppe** [comment]
Bijgewerkte files van Karolien:

[statsec_treg.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/5603771/statsec_treg.xlsx)
[statsec_treg_v3.xlsx](https://github.com/provinciesincijfers/gebiedsniveaus/files/5603773/statsec_treg_v3.xlsx)

**Comment by karolienbloemen** [comment]
zie ook issue 122 in [PinC taakopvolging](https://github.com/provinciesincijfers/PinC-taakopvolging/issues/122): meer info + vraag
